[workspace]
members = [
    "ipc",
    "logging",
    "crypto",
    "apps/watchdog",
    "tezos/api",
    "tezos/messages",
    "tezos/identity",
    "tezos/interop",
    "tezos/interop_callback",
    "tezos/encoding",
    "tezos/client",
    "tezos/wrapper",
    "networking",
    "shell",
    "storage",
    "sandbox",
    "light_node",
    "monitoring",
    "protocol_runner",
    "rpc",
    "fuzz/ack_message",
    "fuzz/advertise_message",
    "fuzz/block_header_message",
    "fuzz/current_branch_message",
    "fuzz/current_head_message",
    "fuzz/connection_message",
    "fuzz/encoding",
    "fuzz/metadata_message",
    "fuzz/operation_message",
    "fuzz/operations_for_blocks_message",
    "fuzz/peer_response_message",
    "fuzz/protocol_message",
]
