[package]
name = "watchdog"
version = "0.10.0"
authors = ["Adrian Nagy <adrian.nagy@simplestaking.com>"]
edition = "2018"
default-run = "watchdog"

[dependencies]
clap = "2.33"
failure = "0.1"
http = "0.2.2"
reqwest = { version = "0.10.10", features = ["json"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
shiplift = { git = "https://github.com/softprops/shiplift.git", branch = "master" }
slack-hook = ""
slog = { version = "2.5", features = ["nested-values"] }
slog-async = "2.5"
slog-term = "2.6"
tokio = { version = "0.2", features = ["full"] }
wait-timeout = "0.2"
shell = { path = "../../shell" }